### ISSUE TITLE
firm addition in makefile

### ISSUE THREAD

**Issue by ghost** [d0k3/HelloEntryPoint#3]
`@firmtool/firmtool.py build $(OUTPUT).firm -n 0x23F00000 -e 0 -D $(OUTPUT).bin -A 0x23F00000 -C NDMA -i`

works, however

`@firmtool/firmtool build $(OUTPUT).firm -n 0x23F00000 -e 0 -D $(OUTPUT).bin -A 0x23F00000 -C NDMA -i`

does not.

**Comment by d0k3** [comment]
The real issue was that I forgot about adding the firmtool submodule.
https://github.com/d0k3/HelloEntryPoint/commit/b1019692ccd91de8bacf68df4af20e92b1b2e063

Fixed, closing.
